server:
  port: 8082

spring:
  application:
    name: candidate-service

  datasource:
    url: jdbc:mysql://localhost:3306/hireready_candidate
    username: root
    password: Password123#

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB


management:
  endpoints:
    web:
      exposure:
        include: health,info
resume:
  storage:
    path: ${user.dir}/uploads/resumes

ai:
  provider: openai
  openai:
    api-key: ${OPENAI_API_KEY}
    model: gpt-4o-mini
    url: https://api.openai.com/v1/chat/completions

services:
  interview-service:
    base-url: http://localhost:8083

interview:
  pass-threshold: 70

